### ISSUE TITLE
Consumer work with STD only

### ISSUE THREAD

**Issue by mmrath** [haraldh/chainerror#1]
This is one of the nicest crates around error handling. After using error-chain and failure and similar ones not I am thinking of just using std only. This crate is close but is there a way clients of `chainerr` write a wrapper such that the dependency on chainerr can be removed easily if a better helper crate comes to existence?

**Comment by haraldh** [comment]
Here is my recommendation:
https://haraldh.github.io/chainerror/tutorial13.html
